// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/echo.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_proto_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Echo back request metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_proto_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EchoWithDelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	DelayMs       int32                  `protobuf:"varint,2,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoWithDelayRequest) Reset() {
	*x = EchoWithDelayRequest{}
	mi := &file_proto_echo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoWithDelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoWithDelayRequest) ProtoMessage() {}

func (x *EchoWithDelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoWithDelayRequest.ProtoReflect.Descriptor instead.
func (*EchoWithDelayRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{2}
}

func (x *EchoWithDelayRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoWithDelayRequest) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type EchoErrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // gRPC status code (0-16)
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"` // Error details message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoErrorRequest) Reset() {
	*x = EchoErrorRequest{}
	mi := &file_proto_echo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoErrorRequest) ProtoMessage() {}

func (x *EchoErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoErrorRequest.ProtoReflect.Descriptor instead.
func (*EchoErrorRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{3}
}

func (x *EchoErrorRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoErrorRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EchoErrorRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type ServerStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                             // Number of responses to stream
	IntervalMs    int32                  `protobuf:"varint,3,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"` // Interval between responses
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStreamRequest) Reset() {
	*x = ServerStreamRequest{}
	mi := &file_proto_echo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamRequest) ProtoMessage() {}

func (x *ServerStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamRequest.ProtoReflect.Descriptor instead.
func (*ServerStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{4}
}

func (x *ServerStreamRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerStreamRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ServerStreamRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

// EchoRequestMetadata - Returns all request metadata in response body
type EchoRequestMetadataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter to specific metadata keys (empty = return all)
	Keys          []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequestMetadataRequest) Reset() {
	*x = EchoRequestMetadataRequest{}
	mi := &file_proto_echo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequestMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequestMetadataRequest) ProtoMessage() {}

func (x *EchoRequestMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequestMetadataRequest.ProtoReflect.Descriptor instead.
func (*EchoRequestMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{5}
}

func (x *EchoRequestMetadataRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type EchoRequestMetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All request metadata as key-value pairs
	Metadata      map[string]*MetadataValues `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequestMetadataResponse) Reset() {
	*x = EchoRequestMetadataResponse{}
	mi := &file_proto_echo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequestMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequestMetadataResponse) ProtoMessage() {}

func (x *EchoRequestMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequestMetadataResponse.ProtoReflect.Descriptor instead.
func (*EchoRequestMetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{6}
}

func (x *EchoRequestMetadataResponse) GetMetadata() map[string]*MetadataValues {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// MetadataValues holds multiple values for a single metadata key
type MetadataValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataValues) Reset() {
	*x = MetadataValues{}
	mi := &file_proto_echo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataValues) ProtoMessage() {}

func (x *MetadataValues) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataValues.ProtoReflect.Descriptor instead.
func (*MetadataValues) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{7}
}

func (x *MetadataValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// EchoWithTrailers - Return response with trailing metadata
type EchoWithTrailersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Trailers      map[string]string      `protobuf:"bytes,2,rep,name=trailers,proto3" json:"trailers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Trailers to send with response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoWithTrailersRequest) Reset() {
	*x = EchoWithTrailersRequest{}
	mi := &file_proto_echo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoWithTrailersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoWithTrailersRequest) ProtoMessage() {}

func (x *EchoWithTrailersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoWithTrailersRequest.ProtoReflect.Descriptor instead.
func (*EchoWithTrailersRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{8}
}

func (x *EchoWithTrailersRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoWithTrailersRequest) GetTrailers() map[string]string {
	if x != nil {
		return x.Trailers
	}
	return nil
}

// EchoLargePayload - Returns large payload of specified size
type EchoLargePayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SizeBytes     int32                  `protobuf:"varint,1,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"` // Size of payload to return (max 10MB)
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`                       // Optional: pattern to repeat (default: 'X')
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoLargePayloadRequest) Reset() {
	*x = EchoLargePayloadRequest{}
	mi := &file_proto_echo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoLargePayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoLargePayloadRequest) ProtoMessage() {}

func (x *EchoLargePayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoLargePayloadRequest.ProtoReflect.Descriptor instead.
func (*EchoLargePayloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{9}
}

func (x *EchoLargePayloadRequest) GetSizeBytes() int32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *EchoLargePayloadRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

type EchoLargePayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ActualSize    int32                  `protobuf:"varint,2,opt,name=actual_size,json=actualSize,proto3" json:"actual_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoLargePayloadResponse) Reset() {
	*x = EchoLargePayloadResponse{}
	mi := &file_proto_echo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoLargePayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoLargePayloadResponse) ProtoMessage() {}

func (x *EchoLargePayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoLargePayloadResponse.ProtoReflect.Descriptor instead.
func (*EchoLargePayloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{10}
}

func (x *EchoLargePayloadResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EchoLargePayloadResponse) GetActualSize() int32 {
	if x != nil {
		return x.ActualSize
	}
	return 0
}

// EchoDeadline - Echo the remaining deadline/timeout
type EchoDeadlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoDeadlineRequest) Reset() {
	*x = EchoDeadlineRequest{}
	mi := &file_proto_echo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoDeadlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoDeadlineRequest) ProtoMessage() {}

func (x *EchoDeadlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoDeadlineRequest.ProtoReflect.Descriptor instead.
func (*EchoDeadlineRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{11}
}

func (x *EchoDeadlineRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoDeadlineResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Message             string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	DeadlineRemainingMs int64                  `protobuf:"varint,2,opt,name=deadline_remaining_ms,json=deadlineRemainingMs,proto3" json:"deadline_remaining_ms,omitempty"` // -1 if no deadline set
	HasDeadline         bool                   `protobuf:"varint,3,opt,name=has_deadline,json=hasDeadline,proto3" json:"has_deadline,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EchoDeadlineResponse) Reset() {
	*x = EchoDeadlineResponse{}
	mi := &file_proto_echo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoDeadlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoDeadlineResponse) ProtoMessage() {}

func (x *EchoDeadlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoDeadlineResponse.ProtoReflect.Descriptor instead.
func (*EchoDeadlineResponse) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{12}
}

func (x *EchoDeadlineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoDeadlineResponse) GetDeadlineRemainingMs() int64 {
	if x != nil {
		return x.DeadlineRemainingMs
	}
	return 0
}

func (x *EchoDeadlineResponse) GetHasDeadline() bool {
	if x != nil {
		return x.HasDeadline
	}
	return false
}

// EchoErrorWithDetails - Return error with rich error details (google.rpc.Status)
type EchoErrorWithDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // gRPC status code (0-16)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message
	Details       []*ErrorDetail         `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"` // Rich error details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoErrorWithDetailsRequest) Reset() {
	*x = EchoErrorWithDetailsRequest{}
	mi := &file_proto_echo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoErrorWithDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoErrorWithDetailsRequest) ProtoMessage() {}

func (x *EchoErrorWithDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoErrorWithDetailsRequest.ProtoReflect.Descriptor instead.
func (*EchoErrorWithDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{13}
}

func (x *EchoErrorWithDetailsRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EchoErrorWithDetailsRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoErrorWithDetailsRequest) GetDetails() []*ErrorDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

type ErrorDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // Detail type: "bad_request", "retry_info", "debug_info", "quota_failure"
	// Fields for BadRequest
	FieldViolations []*FieldViolation `protobuf:"bytes,2,rep,name=field_violations,json=fieldViolations,proto3" json:"field_violations,omitempty"`
	// Fields for RetryInfo
	RetryDelayMs int64 `protobuf:"varint,3,opt,name=retry_delay_ms,json=retryDelayMs,proto3" json:"retry_delay_ms,omitempty"`
	// Fields for DebugInfo
	StackEntries []string `protobuf:"bytes,4,rep,name=stack_entries,json=stackEntries,proto3" json:"stack_entries,omitempty"`
	DebugDetail  string   `protobuf:"bytes,5,opt,name=debug_detail,json=debugDetail,proto3" json:"debug_detail,omitempty"`
	// Fields for QuotaFailure
	QuotaViolations []*QuotaViolation `protobuf:"bytes,6,rep,name=quota_violations,json=quotaViolations,proto3" json:"quota_violations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_proto_echo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{14}
}

func (x *ErrorDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ErrorDetail) GetFieldViolations() []*FieldViolation {
	if x != nil {
		return x.FieldViolations
	}
	return nil
}

func (x *ErrorDetail) GetRetryDelayMs() int64 {
	if x != nil {
		return x.RetryDelayMs
	}
	return 0
}

func (x *ErrorDetail) GetStackEntries() []string {
	if x != nil {
		return x.StackEntries
	}
	return nil
}

func (x *ErrorDetail) GetDebugDetail() string {
	if x != nil {
		return x.DebugDetail
	}
	return ""
}

func (x *ErrorDetail) GetQuotaViolations() []*QuotaViolation {
	if x != nil {
		return x.QuotaViolations
	}
	return nil
}

type FieldViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldViolation) Reset() {
	*x = FieldViolation{}
	mi := &file_proto_echo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldViolation) ProtoMessage() {}

func (x *FieldViolation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldViolation.ProtoReflect.Descriptor instead.
func (*FieldViolation) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{15}
}

func (x *FieldViolation) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldViolation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type QuotaViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaViolation) Reset() {
	*x = QuotaViolation{}
	mi := &file_proto_echo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaViolation) ProtoMessage() {}

func (x *QuotaViolation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaViolation.ProtoReflect.Descriptor instead.
func (*QuotaViolation) Descriptor() ([]byte, []int) {
	return file_proto_echo_proto_rawDescGZIP(), []int{16}
}

func (x *QuotaViolation) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *QuotaViolation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_echo_proto protoreflect.FileDescriptor

const file_proto_echo_proto_rawDesc = "" +
	"\n" +
	"\x10proto/echo.proto\x12\aecho.v1\"'\n" +
	"\vEchoRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xa6\x01\n" +
	"\fEchoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12?\n" +
	"\bmetadata\x18\x02 \x03(\v2#.echo.v1.EchoResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x14EchoWithDelayRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x19\n" +
	"\bdelay_ms\x18\x02 \x01(\x05R\adelayMs\"Z\n" +
	"\x10EchoErrorRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"f\n" +
	"\x13ServerStreamRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1f\n" +
	"\vinterval_ms\x18\x03 \x01(\x05R\n" +
	"intervalMs\"0\n" +
	"\x1aEchoRequestMetadataRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"\xc3\x01\n" +
	"\x1bEchoRequestMetadataResponse\x12N\n" +
	"\bmetadata\x18\x01 \x03(\v22.echo.v1.EchoRequestMetadataResponse.MetadataEntryR\bmetadata\x1aT\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.echo.v1.MetadataValuesR\x05value:\x028\x01\"(\n" +
	"\x0eMetadataValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xbc\x01\n" +
	"\x17EchoWithTrailersRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12J\n" +
	"\btrailers\x18\x02 \x03(\v2..echo.v1.EchoWithTrailersRequest.TrailersEntryR\btrailers\x1a;\n" +
	"\rTrailersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x17EchoLargePayloadRequest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x01 \x01(\x05R\tsizeBytes\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\"U\n" +
	"\x18EchoLargePayloadResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1f\n" +
	"\vactual_size\x18\x02 \x01(\x05R\n" +
	"actualSize\"/\n" +
	"\x13EchoDeadlineRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x87\x01\n" +
	"\x14EchoDeadlineResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x122\n" +
	"\x15deadline_remaining_ms\x18\x02 \x01(\x03R\x13deadlineRemainingMs\x12!\n" +
	"\fhas_deadline\x18\x03 \x01(\bR\vhasDeadline\"{\n" +
	"\x1bEchoErrorWithDetailsRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\adetails\x18\x03 \x03(\v2\x14.echo.v1.ErrorDetailR\adetails\"\x97\x02\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12B\n" +
	"\x10field_violations\x18\x02 \x03(\v2\x17.echo.v1.FieldViolationR\x0ffieldViolations\x12$\n" +
	"\x0eretry_delay_ms\x18\x03 \x01(\x03R\fretryDelayMs\x12#\n" +
	"\rstack_entries\x18\x04 \x03(\tR\fstackEntries\x12!\n" +
	"\fdebug_detail\x18\x05 \x01(\tR\vdebugDetail\x12B\n" +
	"\x10quota_violations\x18\x06 \x03(\v2\x17.echo.v1.QuotaViolationR\x0fquotaViolations\"H\n" +
	"\x0eFieldViolation\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"L\n" +
	"\x0eQuotaViolation\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription2\xb9\x06\n" +
	"\x04Echo\x123\n" +
	"\x04Echo\x12\x14.echo.v1.EchoRequest\x1a\x15.echo.v1.EchoResponse\x12E\n" +
	"\rEchoWithDelay\x12\x1d.echo.v1.EchoWithDelayRequest\x1a\x15.echo.v1.EchoResponse\x12=\n" +
	"\tEchoError\x12\x19.echo.v1.EchoErrorRequest\x1a\x15.echo.v1.EchoResponse\x12`\n" +
	"\x13EchoRequestMetadata\x12#.echo.v1.EchoRequestMetadataRequest\x1a$.echo.v1.EchoRequestMetadataResponse\x12K\n" +
	"\x10EchoWithTrailers\x12 .echo.v1.EchoWithTrailersRequest\x1a\x15.echo.v1.EchoResponse\x12W\n" +
	"\x10EchoLargePayload\x12 .echo.v1.EchoLargePayloadRequest\x1a!.echo.v1.EchoLargePayloadResponse\x12K\n" +
	"\fEchoDeadline\x12\x1c.echo.v1.EchoDeadlineRequest\x1a\x1d.echo.v1.EchoDeadlineResponse\x12S\n" +
	"\x14EchoErrorWithDetails\x12$.echo.v1.EchoErrorWithDetailsRequest\x1a\x15.echo.v1.EchoResponse\x12E\n" +
	"\fServerStream\x12\x1c.echo.v1.ServerStreamRequest\x1a\x15.echo.v1.EchoResponse0\x01\x12=\n" +
	"\fClientStream\x12\x14.echo.v1.EchoRequest\x1a\x15.echo.v1.EchoResponse(\x01\x12F\n" +
	"\x13BidirectionalStream\x12\x14.echo.v1.EchoRequest\x1a\x15.echo.v1.EchoResponse(\x010\x01B5Z3github.com/jsr-probitas/dockerfiles/echo-grpc/protob\x06proto3"

var (
	file_proto_echo_proto_rawDescOnce sync.Once
	file_proto_echo_proto_rawDescData []byte
)

func file_proto_echo_proto_rawDescGZIP() []byte {
	file_proto_echo_proto_rawDescOnce.Do(func() {
		file_proto_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_echo_proto_rawDesc), len(file_proto_echo_proto_rawDesc)))
	})
	return file_proto_echo_proto_rawDescData
}

var file_proto_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_echo_proto_goTypes = []any{
	(*EchoRequest)(nil),                 // 0: echo.v1.EchoRequest
	(*EchoResponse)(nil),                // 1: echo.v1.EchoResponse
	(*EchoWithDelayRequest)(nil),        // 2: echo.v1.EchoWithDelayRequest
	(*EchoErrorRequest)(nil),            // 3: echo.v1.EchoErrorRequest
	(*ServerStreamRequest)(nil),         // 4: echo.v1.ServerStreamRequest
	(*EchoRequestMetadataRequest)(nil),  // 5: echo.v1.EchoRequestMetadataRequest
	(*EchoRequestMetadataResponse)(nil), // 6: echo.v1.EchoRequestMetadataResponse
	(*MetadataValues)(nil),              // 7: echo.v1.MetadataValues
	(*EchoWithTrailersRequest)(nil),     // 8: echo.v1.EchoWithTrailersRequest
	(*EchoLargePayloadRequest)(nil),     // 9: echo.v1.EchoLargePayloadRequest
	(*EchoLargePayloadResponse)(nil),    // 10: echo.v1.EchoLargePayloadResponse
	(*EchoDeadlineRequest)(nil),         // 11: echo.v1.EchoDeadlineRequest
	(*EchoDeadlineResponse)(nil),        // 12: echo.v1.EchoDeadlineResponse
	(*EchoErrorWithDetailsRequest)(nil), // 13: echo.v1.EchoErrorWithDetailsRequest
	(*ErrorDetail)(nil),                 // 14: echo.v1.ErrorDetail
	(*FieldViolation)(nil),              // 15: echo.v1.FieldViolation
	(*QuotaViolation)(nil),              // 16: echo.v1.QuotaViolation
	nil,                                 // 17: echo.v1.EchoResponse.MetadataEntry
	nil,                                 // 18: echo.v1.EchoRequestMetadataResponse.MetadataEntry
	nil,                                 // 19: echo.v1.EchoWithTrailersRequest.TrailersEntry
}
var file_proto_echo_proto_depIdxs = []int32{
	17, // 0: echo.v1.EchoResponse.metadata:type_name -> echo.v1.EchoResponse.MetadataEntry
	18, // 1: echo.v1.EchoRequestMetadataResponse.metadata:type_name -> echo.v1.EchoRequestMetadataResponse.MetadataEntry
	19, // 2: echo.v1.EchoWithTrailersRequest.trailers:type_name -> echo.v1.EchoWithTrailersRequest.TrailersEntry
	14, // 3: echo.v1.EchoErrorWithDetailsRequest.details:type_name -> echo.v1.ErrorDetail
	15, // 4: echo.v1.ErrorDetail.field_violations:type_name -> echo.v1.FieldViolation
	16, // 5: echo.v1.ErrorDetail.quota_violations:type_name -> echo.v1.QuotaViolation
	7,  // 6: echo.v1.EchoRequestMetadataResponse.MetadataEntry.value:type_name -> echo.v1.MetadataValues
	0,  // 7: echo.v1.Echo.Echo:input_type -> echo.v1.EchoRequest
	2,  // 8: echo.v1.Echo.EchoWithDelay:input_type -> echo.v1.EchoWithDelayRequest
	3,  // 9: echo.v1.Echo.EchoError:input_type -> echo.v1.EchoErrorRequest
	5,  // 10: echo.v1.Echo.EchoRequestMetadata:input_type -> echo.v1.EchoRequestMetadataRequest
	8,  // 11: echo.v1.Echo.EchoWithTrailers:input_type -> echo.v1.EchoWithTrailersRequest
	9,  // 12: echo.v1.Echo.EchoLargePayload:input_type -> echo.v1.EchoLargePayloadRequest
	11, // 13: echo.v1.Echo.EchoDeadline:input_type -> echo.v1.EchoDeadlineRequest
	13, // 14: echo.v1.Echo.EchoErrorWithDetails:input_type -> echo.v1.EchoErrorWithDetailsRequest
	4,  // 15: echo.v1.Echo.ServerStream:input_type -> echo.v1.ServerStreamRequest
	0,  // 16: echo.v1.Echo.ClientStream:input_type -> echo.v1.EchoRequest
	0,  // 17: echo.v1.Echo.BidirectionalStream:input_type -> echo.v1.EchoRequest
	1,  // 18: echo.v1.Echo.Echo:output_type -> echo.v1.EchoResponse
	1,  // 19: echo.v1.Echo.EchoWithDelay:output_type -> echo.v1.EchoResponse
	1,  // 20: echo.v1.Echo.EchoError:output_type -> echo.v1.EchoResponse
	6,  // 21: echo.v1.Echo.EchoRequestMetadata:output_type -> echo.v1.EchoRequestMetadataResponse
	1,  // 22: echo.v1.Echo.EchoWithTrailers:output_type -> echo.v1.EchoResponse
	10, // 23: echo.v1.Echo.EchoLargePayload:output_type -> echo.v1.EchoLargePayloadResponse
	12, // 24: echo.v1.Echo.EchoDeadline:output_type -> echo.v1.EchoDeadlineResponse
	1,  // 25: echo.v1.Echo.EchoErrorWithDetails:output_type -> echo.v1.EchoResponse
	1,  // 26: echo.v1.Echo.ServerStream:output_type -> echo.v1.EchoResponse
	1,  // 27: echo.v1.Echo.ClientStream:output_type -> echo.v1.EchoResponse
	1,  // 28: echo.v1.Echo.BidirectionalStream:output_type -> echo.v1.EchoResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_echo_proto_init() }
func file_proto_echo_proto_init() {
	if File_proto_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_echo_proto_rawDesc), len(file_proto_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_echo_proto_goTypes,
		DependencyIndexes: file_proto_echo_proto_depIdxs,
		MessageInfos:      file_proto_echo_proto_msgTypes,
	}.Build()
	File_proto_echo_proto = out.File
	file_proto_echo_proto_goTypes = nil
	file_proto_echo_proto_depIdxs = nil
}
